/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Ventanas;

import com.mycompany.mavenproject1.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author sano2
 */
public class FormularioPersona extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPersona
     */
    public FormularioPersona() {
        initComponents();
        this.Team = null;
    }
    private final Equipo Team;

    public FormularioPersona(Equipo Team) {
        this.Team = Team;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        CampoNombre = new javax.swing.JTextField();
        CampoCedula = new javax.swing.JTextField();
        CampoTelefono = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        CajaGenero = new javax.swing.JComboBox<>();
        BotonTecnico = new javax.swing.JRadioButton();
        BotonJugador = new javax.swing.JRadioButton();
        BotonLider = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        CajaDiaNacimiento = new javax.swing.JComboBox<>();
        CajaMesNacimiento = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CajaAñoNacimiento = new javax.swing.JComboBox<>();
        BotonContinuar = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();
        CajaNumeroPersonas = new javax.swing.JTextField();
        CajaPersonasRegistradas = new javax.swing.JTextField();
        NombreEquipoNuevo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 285, -1));
        jPanel1.add(CampoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 285, -1));
        jPanel1.add(CampoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 285, -1));
        jPanel1.add(CampoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 285, -1));

        CajaGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEMENINO", "MASCULINO", "MIXTO", " ", " " }));
        jPanel1.add(CajaGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 46));

        buttonGroup1.add(BotonTecnico);
        BotonTecnico.setText("TÉCNICO");
        jPanel1.add(BotonTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 86, -1));

        buttonGroup1.add(BotonJugador);
        BotonJugador.setText("JUGADOR");
        jPanel1.add(BotonJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        buttonGroup1.add(BotonLider);
        BotonLider.setText("LIDER JUGADOR");
        jPanel1.add(BotonLider, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        jLabel11.setText("DIA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 287, -1, 24));

        CajaDiaNacimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(CajaDiaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 317, 99, -1));

        CajaMesNacimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel1.add(CajaMesNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 317, 105, -1));

        jLabel12.setText("MES");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 291, -1, -1));

        jLabel13.setText("AÑO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 291, -1, -1));

        CajaAñoNacimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));
        jPanel1.add(CajaAñoNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 317, 104, -1));

        BotonContinuar.setText("CONTINUAR");
        BotonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 110, 40));

        BotonAtras.setText("ATRAS");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 120, 40));

        CajaNumeroPersonas.setEditable(false);
        CajaNumeroPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CajaNumeroPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaNumeroPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(CajaNumeroPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 70, -1));

        CajaPersonasRegistradas.setEditable(false);
        CajaPersonasRegistradas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CajaPersonasRegistradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaPersonasRegistradasActionPerformed(evt);
            }
        });
        jPanel1.add(CajaPersonasRegistradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 87, -1));

        NombreEquipoNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(NombreEquipoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 194, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("NOMBRE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("CEDULA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("TELÉFONO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("CORREO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("GÉNERO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("ELIJA EL TIPO DE PARTICIPANTE");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("FECHA DE NACIMIENTO");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 180, 30));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("CANTIDAD DE MIEMBROS");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, 30));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("CANTIDAD DE REGISTRADOS");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonAtrasActionPerformed

    private void CajaNumeroPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaNumeroPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaNumeroPersonasActionPerformed

    private void CajaPersonasRegistradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaPersonasRegistradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaPersonasRegistradasActionPerformed

    private void BotonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonContinuarActionPerformed
//      
        //verifico que los campos de texto no estén vacios 
        if (CampoNombre.getText().isEmpty() || CampoCedula.getText().isEmpty()
                || CampoTelefono.getText().isEmpty() || CampoCorreo.getText().isEmpty() || buttonGroup1.getSelection() == null) {

            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos y seleccione las opciones");
        } else {

            if (FormularioTorneo.CajaTipoTorneo.getSelectedItem().equals("Ajedrez") && BotonLider.isSelected()) {
                JOptionPane.showMessageDialog(null, "el equipo solo puede contener un Tecnico y un Jugador");
                
            } else {
                int cantErrores = 0;

                int cantPersonasRegistradas = Integer.parseInt(CajaPersonasRegistradas.getText());;
                //creo la persona y seteo sus atributos
                Persona NuevoParticipante = new Persona();
                NuevoParticipante.setNombre((String) CampoNombre.getText());
                NuevoParticipante.setCedula((String) CampoCedula.getText());

                if (FormularioTorneo.generoTorneo.equals((String) CajaGenero.getSelectedItem())) {
                    NuevoParticipante.setGenero((String) CajaGenero.getSelectedItem());

                } else {
                    cantErrores++;
                }

                NuevoParticipante.setTelefono((String) CampoTelefono.getText());
                NuevoParticipante.setCorreo((String) CampoCorreo.getText());

                Fecha FechaNacimientoPersona = new Fecha();
                FechaNacimientoPersona.setDia(Integer.parseInt((String) CajaDiaNacimiento.getSelectedItem()));
                FechaNacimientoPersona.setAño(Integer.parseInt((String) CajaAñoNacimiento.getSelectedItem()));
                FechaNacimientoPersona.setMes(FechaNacimientoPersona.transformar_StringMes((String) CajaMesNacimiento.getSelectedItem()));
                int edad = Fecha.calcular_edad(FechaNacimientoPersona);

                if (FormularioTorneo.LimiteEdad >= edad) {

                    NuevoParticipante.setEdad(edad);

                } else {
                    cantErrores++;
                }

                //atributo fecha, en el formulario torneo explico su funcionamiento
                //creo if´s anidados para verificar si la persona a ingresar es tecnico, jugador o lider
                NuevoParticipante.setFecha_nacimiento(FechaNacimientoPersona);
                if (cantErrores == 0) {
                    if (BotonTecnico.isSelected()) {
                        FormularioEquipo.CampoTecnico.setText((String) CampoNombre.getText());
                        NuevoParticipante.setTipo("TECNICO");
                        Team.setTecnico(NuevoParticipante);
                        JOptionPane.showMessageDialog(null, "Registro exitoso del Tecnico");
                    } else if (BotonLider.isSelected()) {
                        FormularioEquipo.CampoLider.setText((String) CampoNombre.getText());
                        NuevoParticipante.setTipo("LIDER_JUGADOR");
                        Team.setLider(NuevoParticipante);
                        JOptionPane.showMessageDialog(null, "Registro exitoso del Lider");
                    } else if (BotonJugador.isSelected()) {
                        NuevoParticipante.setTipo("JUGADOR");
                        FormularioEquipo.ListadoParticipantes.add(NuevoParticipante);
                        JOptionPane.showMessageDialog(null, "Registro exitoso del Jugador");
                    }
                    FormularioEquipo.MiembrosRegistrados++;
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese los datos correctamente");
                    cantErrores = 0;
                }
            }
        }
    }//GEN-LAST:event_BotonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonContinuar;
    private javax.swing.JRadioButton BotonJugador;
    private javax.swing.JRadioButton BotonLider;
    private javax.swing.JRadioButton BotonTecnico;
    private javax.swing.JComboBox<String> CajaAñoNacimiento;
    private javax.swing.JComboBox<String> CajaDiaNacimiento;
    private javax.swing.JComboBox<String> CajaGenero;
    private javax.swing.JComboBox<String> CajaMesNacimiento;
    public static javax.swing.JTextField CajaNumeroPersonas;
    public static javax.swing.JTextField CajaPersonasRegistradas;
    private javax.swing.JTextField CampoCedula;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoTelefono;
    public static javax.swing.JLabel NombreEquipoNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
