/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Ventanas;

import com.mycompany.mavenproject1.Datos;
import com.mycompany.mavenproject1.Torneo;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author sano2
 */
public class InterfazPrincipal extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form InterfazPrincipal
     */
    public static ArrayList<Torneo> torneosFutbol;
    public static ArrayList<Torneo> torneosBasket;
    public static ArrayList<Torneo> torneosAjedrez;
    public static ArrayList<Torneo> torneosVolley;
    public Datos datos = Datos.obtenerInstancia();

    public InterfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonRegistrarTorneo = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonGuardarDatos = new javax.swing.JButton();
        BotonCargarDatos = new javax.swing.JButton();
        BotonVerTorneos = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonRegistrarTorneo.setText("REGISTRAR NUEVO TORNEO");
        BotonRegistrarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarTorneoActionPerformed(evt);
            }
        });

        BotonSalir.setText("SALIR");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonGuardarDatos.setText("GUARDAR DATOS");
        BotonGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarDatosActionPerformed(evt);
            }
        });

        BotonCargarDatos.setText("CARGAR DATOS GUARDADOS");
        BotonCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarDatosActionPerformed(evt);
            }
        });

        BotonVerTorneos.setText("VER TORNEOS EN CURSO");
        BotonVerTorneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerTorneosActionPerformed(evt);
            }
        });

        Logo.setText("LOGO BIEN CRIMINAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonGuardarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonCargarDatos)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotonVerTorneos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonRegistrarTorneo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonRegistrarTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo))
                .addGap(37, 37, 37)
                .addComponent(BotonVerTorneos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(BotonGuardarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonRegistrarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarTorneoActionPerformed
        // Abre el formulario para crear un torneo

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioTorneo().setVisible(true);
            }
        });
    }//GEN-LAST:event_BotonRegistrarTorneoActionPerformed

    private void BotonVerTorneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerTorneosActionPerformed
        // llamo a la ventana ver torneo en curso
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerTorneoEnCurso().setVisible(true);
            }
        });
    }//GEN-LAST:event_BotonVerTorneosActionPerformed

    private void BotonGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarDatosActionPerformed
        try (ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("datos.ser"))) {
            System.out.println("Tamaño de torneosFutbol: " + datos.listado_torneos_futbol.size());
            System.out.println("Tamaño de torneosBasket: " + datos.listado_torneos_basket.size());
            System.out.println("Tamaño de torneosAjedrez: " + datos.listado_torneos_ajedrez.size());
            System.out.println("Tamaño de torneosVolley: " + datos.listado_torneos_volley.size());
            out.writeObject(datos);
            System.out.println("Dirección de memoria de datos al guardar: " + System.identityHashCode(datos));

            JOptionPane.showMessageDialog(null, "datos guardados");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BotonGuardarDatosActionPerformed

    private void BotonCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarDatosActionPerformed

        ;
        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream("datos.ser"))) {
            Datos datosCargados = Datos.obtenerInstancia();
            datosCargados = (Datos) in.readObject();

            datos.listado_torneos_futbol.clear();
            datos.listado_torneos_futbol.addAll(datosCargados.listado_torneos_futbol);

            datos.listado_torneos_basket.clear();
            datos.listado_torneos_basket.addAll(datosCargados.listado_torneos_basket);

            datos.listado_torneos_ajedrez.clear();
            datos.listado_torneos_ajedrez.addAll(datosCargados.listado_torneos_ajedrez);

            datos.listado_torneos_volley.clear();
            datos.listado_torneos_volley.addAll(datosCargados.listado_torneos_volley);
            //Acceder a los ArrayLists de datos
            System.out.println("Tamaño de torneosFutbol: " + datos.listado_torneos_futbol.size());
            System.out.println("Tamaño de torneosBasket: " + datos.listado_torneos_basket.size());
            System.out.println("Tamaño de torneosAjedrez: " + datos.listado_torneos_ajedrez.size());
            System.out.println("Tamaño de torneosVolley: " + datos.listado_torneos_volley.size());
            
            System.out.println("Dirección de memoria de datos al cargar: " + System.identityHashCode(datos));

            JOptionPane.showMessageDialog(null, "datos cargados");
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_BotonCargarDatosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCargarDatos;
    private javax.swing.JButton BotonGuardarDatos;
    private javax.swing.JButton BotonRegistrarTorneo;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonVerTorneos;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
