/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Ventanas;

import com.mycompany.mavenproject1.*;

/**
 *
 * @author angel
 */
public class VerDatos extends javax.swing.JFrame {
    
    //Se crea atributo torneo para poder llamarla cuando se desee
    public static Torneo torneo_en_cuestion;

    /**
     * Creates new form VerDatos
     */
    public VerDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDeFondo = new javax.swing.JPanel();
        CampoDato1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoDato2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoDato3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoDato4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoDato5 = new javax.swing.JTextField();
        BotonTablaDePosiciones = new javax.swing.JButton();
        BotonProximosEnfrentamientos = new javax.swing.JButton();
        BotonCerrar = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        MesInicioInscripciones = new javax.swing.JComboBox<>();
        DiaInicioInscripciones = new javax.swing.JComboBox<>();
        AñoInicioInscripciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        DiaCierreInscripciones = new javax.swing.JComboBox<>();
        MesCierreInscripciones = new javax.swing.JComboBox<>();
        AñoCierreInscripciones = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        DiaInicioTorneo = new javax.swing.JComboBox<>();
        MesInicioTorneo = new javax.swing.JComboBox<>();
        AñoInicioTorneo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDeFondo.setPreferredSize(new java.awt.Dimension(1000, 600));

        CampoDato1.setEditable(false);
        CampoDato1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CampoDato1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoDato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDato1ActionPerformed(evt);
            }
        });

        jLabel2.setText("GÉNERO");

        CampoDato2.setEditable(false);
        CampoDato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDato2ActionPerformed(evt);
            }
        });

        jLabel3.setText("CARACTER");

        CampoDato3.setEditable(false);

        jLabel4.setText("LUGAR");

        CampoDato4.setEditable(false);

        jLabel5.setText("ESTADO");

        CampoDato5.setEditable(false);

        BotonTablaDePosiciones.setText("TABLA DE POSICIONES");
        BotonTablaDePosiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTablaDePosicionesActionPerformed(evt);
            }
        });

        BotonProximosEnfrentamientos.setText("ENFRENTAMIENTOS");
        BotonProximosEnfrentamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProximosEnfrentamientosActionPerformed(evt);
            }
        });

        BotonCerrar.setText("X");
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });

        BotonVolver.setText("<");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        MesInicioInscripciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        DiaInicioInscripciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        AñoInicioInscripciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033" }));

        jLabel1.setText("FECHA INICIO INSCRIPCIONES");

        DiaCierreInscripciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        MesCierreInscripciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        AñoCierreInscripciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033" }));

        jLabel6.setText("FECHA CIERRE INSCRIPCIONES");

        DiaInicioTorneo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        MesInicioTorneo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        AñoInicioTorneo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033" }));

        jLabel7.setText("FECHA INICIO TORNEO");

        javax.swing.GroupLayout PanelDeFondoLayout = new javax.swing.GroupLayout(PanelDeFondo);
        PanelDeFondo.setLayout(PanelDeFondoLayout);
        PanelDeFondoLayout.setHorizontalGroup(
            PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeFondoLayout.createSequentialGroup()
                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDeFondoLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(CampoDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDeFondoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CampoDato3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(CampoDato5)))
                        .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDeFondoLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelDeFondoLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelDeFondoLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CampoDato4)
                                            .addGroup(PanelDeFondoLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(PanelDeFondoLayout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AñoCierreInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonVolver))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelDeFondoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DiaInicioTorneo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiaInicioInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDeFondoLayout.createSequentialGroup()
                                .addComponent(MesInicioInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AñoInicioInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(DiaCierreInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(MesCierreInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDeFondoLayout.createSequentialGroup()
                                .addComponent(MesInicioTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AñoInicioTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelDeFondoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel7))
                    .addGroup(PanelDeFondoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(BotonTablaDePosiciones)
                        .addGap(110, 110, 110)
                        .addComponent(BotonProximosEnfrentamientos)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PanelDeFondoLayout.setVerticalGroup(
            PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeFondoLayout.createSequentialGroup()
                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoDato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CampoDato5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CampoDato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(CampoDato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(CampoDato4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDeFondoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDeFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MesInicioInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiaInicioInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñoInicioInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiaCierreInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesCierreInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñoCierreInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaInicioTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MesInicioTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñoInicioTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PanelDeFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonTablaDePosiciones)
                    .addComponent(BotonProximosEnfrentamientos))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(PanelDeFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoDato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDato2ActionPerformed

    private void BotonProximosEnfrentamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProximosEnfrentamientosActionPerformed
        Enfrentamientos.ver_enfrentamientos(torneo_en_cuestion);
    }//GEN-LAST:event_BotonProximosEnfrentamientosActionPerformed

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
       this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonTablaDePosicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTablaDePosicionesActionPerformed
        //tablaDePosiciones.NombreTorneoCuestion.setText(torneo_en_cuestion.nombre);
        tablaDePosiciones.ver_ventana(torneo_en_cuestion);
        
    }//GEN-LAST:event_BotonTablaDePosicionesActionPerformed

    private void CampoDato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDato1ActionPerformed

    }//GEN-LAST:event_CampoDato1ActionPerformed
    
    public static void ver_datos(Torneo torneo){ //le llega como parámetro el torneo que queremos consultar
        torneo_en_cuestion=torneo;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new VerDatos().setVisible(true);
                
                CampoDato1.setText(torneo.nombre);
                CampoDato2.setText(torneo.genero);
                CampoDato3.setText(torneo.caracter);
                CampoDato4.setText(torneo.lugar);
                CampoDato5.setText(torneo.estado);
                
            }
        });
        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AñoCierreInscripciones;
    private javax.swing.JComboBox<String> AñoInicioInscripciones;
    private javax.swing.JComboBox<String> AñoInicioTorneo;
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonProximosEnfrentamientos;
    private javax.swing.JButton BotonTablaDePosiciones;
    private javax.swing.JButton BotonVolver;
    public static javax.swing.JTextField CampoDato1;
    public static javax.swing.JTextField CampoDato2;
    public static javax.swing.JTextField CampoDato3;
    public static javax.swing.JTextField CampoDato4;
    public static javax.swing.JTextField CampoDato5;
    private javax.swing.JComboBox<String> DiaCierreInscripciones;
    private javax.swing.JComboBox<String> DiaInicioInscripciones;
    private javax.swing.JComboBox<String> DiaInicioTorneo;
    private javax.swing.JComboBox<String> MesCierreInscripciones;
    private javax.swing.JComboBox<String> MesInicioInscripciones;
    private javax.swing.JComboBox<String> MesInicioTorneo;
    public javax.swing.JPanel PanelDeFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
