/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.Ventanas;

import com.mycompany.mavenproject1.*;

/**
 *
 * @author Alexis Chapal
 */
public class VerTorneoFutbol extends javax.swing.JFrame {

    /**
     * Creates new form VerTorneoFutbol
     */
    public VerTorneoFutbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        VerDatosTorneo1 = new javax.swing.JButton();
        NombreTorneo1 = new javax.swing.JTextField();
        NombreTorneo3 = new javax.swing.JTextField();
        VerDatosTorneo3 = new javax.swing.JButton();
        NombreTorneo2 = new javax.swing.JTextField();
        VerDatosTorneo2 = new javax.swing.JButton();
        NombreTorneo4 = new javax.swing.JTextField();
        VerDatosTorneo4 = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerDatosTorneo1.setText("Datos");
        VerDatosTorneo1.setEnabled(false);
        VerDatosTorneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDatosTorneo1ActionPerformed(evt);
            }
        });
        jPanel2.add(VerDatosTorneo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 58, -1, -1));

        NombreTorneo1.setEditable(false);
        NombreTorneo1.setText("AQUÍ APERECE EL NOMBRE");
        NombreTorneo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTorneo1ActionPerformed(evt);
            }
        });
        jPanel2.add(NombreTorneo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, 196, -1));

        NombreTorneo3.setEditable(false);
        NombreTorneo3.setText("AQUÍ APERECE EL NOMBRE");
        jPanel2.add(NombreTorneo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 170, -1));

        VerDatosTorneo3.setText("Datos");
        VerDatosTorneo3.setEnabled(false);
        VerDatosTorneo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDatosTorneo3ActionPerformed(evt);
            }
        });
        jPanel2.add(VerDatosTorneo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        NombreTorneo2.setEditable(false);
        NombreTorneo2.setText("AQUÍ APERECE EL NOMBRE");
        jPanel2.add(NombreTorneo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 165, -1, -1));

        VerDatosTorneo2.setText("Datos");
        VerDatosTorneo2.setEnabled(false);
        VerDatosTorneo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDatosTorneo2ActionPerformed(evt);
            }
        });
        jPanel2.add(VerDatosTorneo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 205, -1, -1));

        NombreTorneo4.setEditable(false);
        NombreTorneo4.setText("AQUÍ APERECE EL NOMBRE");
        NombreTorneo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTorneo4ActionPerformed(evt);
            }
        });
        jPanel2.add(NombreTorneo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 170, -1));

        VerDatosTorneo4.setText("Datos");
        VerDatosTorneo4.setEnabled(false);
        VerDatosTorneo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDatosTorneo4ActionPerformed(evt);
            }
        });
        jPanel2.add(VerDatosTorneo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        BotonSalir.setText("SALIR");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        jPanel2.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 143, -1));

        BotonAtras.setText("ATRAS");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 140, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerDatosTorneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDatosTorneo1ActionPerformed
        
        
        VerDatos.ver_datos(Datos.obtenerInstancia().listado_torneos_futbol.get(0),0);//mandamos como parámetro el torneo que queremos consultar
    }//GEN-LAST:event_VerDatosTorneo1ActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonAtrasActionPerformed

    private void NombreTorneo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTorneo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTorneo4ActionPerformed

    private void NombreTorneo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTorneo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTorneo1ActionPerformed

    private void VerDatosTorneo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDatosTorneo2ActionPerformed
        VerDatos.ver_datos(Datos.obtenerInstancia().listado_torneos_futbol.get(1),1);//mandamos como parámetro el torneo que queremos consultar
    }//GEN-LAST:event_VerDatosTorneo2ActionPerformed

    private void VerDatosTorneo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDatosTorneo3ActionPerformed
        VerDatos.ver_datos(Datos.obtenerInstancia().listado_torneos_futbol.get(2),2);//mandamos como parámetro el torneo que queremos consultar
    }//GEN-LAST:event_VerDatosTorneo3ActionPerformed

    private void VerDatosTorneo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDatosTorneo4ActionPerformed
        VerDatos.ver_datos(Datos.obtenerInstancia().listado_torneos_futbol.get(3),3);//mandamos como parámetro el torneo que queremos consultar
    }//GEN-LAST:event_VerDatosTorneo4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonSalir;
    public static javax.swing.JTextField NombreTorneo1;
    public static javax.swing.JTextField NombreTorneo2;
    public static javax.swing.JTextField NombreTorneo3;
    public static javax.swing.JTextField NombreTorneo4;
    public static javax.swing.JButton VerDatosTorneo1;
    public static javax.swing.JButton VerDatosTorneo2;
    public static javax.swing.JButton VerDatosTorneo3;
    public static javax.swing.JButton VerDatosTorneo4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
